name: csec-dev
services:
  - name: backend-web
    git:
      branch: main
      repo_clone_url: https://github.com/yetmgetaredahegn/CSEC_Dev.git
    source_dir: backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    run_command: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000
    envs:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: "change-me"
        type: SECRET
      - key: DJANGO_ALLOWED_HOSTS
        value: "your-backend-domain"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain"
      - key: POSTGRES_DB
        value: "csec_dev"
      - key: POSTGRES_USER
        value: "csec_user"
      - key: POSTGRES_PASSWORD
        value: "change-me"
        type: SECRET
      - key: POSTGRES_HOST
        value: "db-host"
      - key: POSTGRES_PORT
        value: "5432"
      - key: REDIS_URL
        value: "redis://your-redis-host:6379/0"
      - key: CELERY_BROKER_URL
        value: "redis://your-redis-host:6379/0"
      - key: CELERY_RESULT_BACKEND
        value: "redis://your-redis-host:6379/0"
      - key: OPENAI_API_KEY
        value: "change-me"
        type: SECRET
      - key: OPENAI_CHAT_MODEL
        value: "gpt-4o-mini"
      - key: OPENAI_EMBED_MODEL
        value: "text-embedding-3-large"
      - key: CHROMA_PERSIST_DIR
        value: "/data/vector_store"
    health_check:
      http_path: /api/ping/
  - name: backend-worker
    git:
      branch: main
      repo_clone_url: https://github.com/yetmgetaredahegn/CSEC_Dev.git
    source_dir: backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: celery -A core worker -l info
    envs:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: "change-me"
        type: SECRET
      - key: DJANGO_ALLOWED_HOSTS
        value: "your-backend-domain"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain"
      - key: POSTGRES_DB
        value: "csec_dev"
      - key: POSTGRES_USER
        value: "csec_user"
      - key: POSTGRES_PASSWORD
        value: "change-me"
        type: SECRET
      - key: POSTGRES_HOST
        value: "db-host"
      - key: POSTGRES_PORT
        value: "5432"
      - key: REDIS_URL
        value: "redis://your-redis-host:6379/0"
      - key: CELERY_BROKER_URL
        value: "redis://your-redis-host:6379/0"
      - key: CELERY_RESULT_BACKEND
        value: "redis://your-redis-host:6379/0"
      - key: OPENAI_API_KEY
        value: "change-me"
        type: SECRET
      - key: OPENAI_CHAT_MODEL
        value: "gpt-4o-mini"
      - key: OPENAI_EMBED_MODEL
        value: "text-embedding-3-large"
      - key: CHROMA_PERSIST_DIR
        value: "/data/vector_store"
